### ISSUE TITLE
recovery.img not include valid file

### ISSUE THREAD

**Issue by thetanmaygupta** [CaptainThrowback/Action-Recovery-Builder#2]
![Screenshot_2022-07-26-22-50-06-264_com android chrome](https://user-images.githubusercontent.com/29389563/181073799-1a20edb1-98bd-4cd6-8ccf-e0855a2263ec.jpg)

Device Tree- https://github.com/thetanmaygupta/twrp_device_xiaomi_light

**Comment by thetanmaygupta** [comment]
![Uploading Screenshot_2022-07-26-23-32-19-953_com.android.chrome.jpg…]()

**Comment by thetanmaygupta** [comment]
![Screenshot_2022-07-26-23-32-19-953_com android chrome](https://user-images.githubusercontent.com/29389563/181079267-22dc2a2f-eee8-4249-bd9b-838bb61eeb43.jpg)

**Comment by CaptainThrowback** [comment]
Not an issue with the builder. Fix your device tree and build the correct target.
