### ISSUE TITLE
multiple board config files

### ISSUE THREAD

**Issue by rosemaryuser** [CaptainThrowback/Action-Recovery-Builder#4]
build/make/core/board_config.mk:137: error: Multiple board config files for TARGET_DEVICE rosemary: device/redmi/rosemary/BoardConfig.mk device/redmi/rosemary/rosemary/BoardConfig.mk.
13:47:55 dumpvars failed with: exit status 1
Device rosemary not found. Attempting to retrieve device repository from OrangeFox Github (http://github.com/OrangeFox).

**Comment by CaptainThrowback** [comment]
I checked your Github and see successful builds. Is this still an issue? Or can I close?

**Comment by rosemaryuser** [comment]
You can close it
